---
- name: Initial Server Setup on Ubuntu 20.04
  hosts: all
  become: true
  vars:
    new_user: deployer
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    allowed_ports:
      - "22"
    packages:
      - ufw
      - fail2ban
      - git
      - curl
      - htop
      - net-tools
  tasks:
    - name: Ensure aptitude is installed
      apt:
        name: aptitude
        state: present
        update_cache: yes

    - name: Create a new user with sudo privileges
      user:
        name: "{{ new_user }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Set up authorized key for the new user
      authorized_key:
        user: "{{ new_user }}"
        key: "{{ ssh_public_key }}"

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Reload SSH service
      service:
        name: ssh
        state: reloaded

    - name: Install essential packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: Set up UFW to allow SSH
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ allowed_ports }}"

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
